// ignore_for_file: constant_identifier_names
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart
part of 'app_pages.dart';

abstract class Routes {
  Routes._();
  static const TEST = _Paths.BOOTOMVIEW_TEST;
  static const WELCOME_SCREENS = _Paths.WELCOME_SCREENS;
  static const LOGIN = _Paths.LOGIN;
  static const FORGOT_PASSWORD = _Paths.FORGOT_PASSWORD;
  static const DASHBOARD = _Paths.DASHBOARD;
  static const MAIN_SCREEN = _Paths.MAIN_SCREEN;
  static const ORACLE_CARDS = _Paths.ORACLE_CARDS;
  static const STORE = _Paths.STORE;
  static const ACCOUNT_SETTINGS = _Paths.ACCOUNT_SETTINGS;
  static const SIDE_MENU = _Paths.SIDE_MENU;
  static const SACRED_RELATIONSHIPS = _Paths.SACRED_RELATIONSHIPS;
  static const KARMIC_RELATIONSHIPS = _Paths.KARMIC_RELATIONSHIPS;
  static const TEACHINGS_DETAILS = _Paths.TEACHINGS_DETAILS;
  static const PROFILE = _Paths.PROFILE;
  static const CHANGE_PASSWORD = _Paths.CHANGE_PASSWORD;
  static const CHANGE_EMAIL = _Paths.CHANGE_EMAIL;
  static const SPIRITUAL_SPOTLIGHT = _Paths.SPIRITUAL_SPOTLIGHT;
  static const BLOGS_LISTING = _Paths.BLOGS_LISTING;
  static const BOOKS_LISTING = _Paths.BOOKS_LISTING;
  static const SESSIONS_LISTING = _Paths.SESSIONS_LISTING;
  static const PROGRAMS_LISTING = _Paths.PROGRAMS_LISTING;
  static const INNER_UNION_ORACLE = _Paths.INNER_UNION_ORACLE;
  static const SUPPORT = _Paths.SUPPORT;
  static const BOOK_DETAILS = _Paths.BOOK_DETAILS;
  static const ABOUT = _Paths.ABOUT;
  static const SET_REMINDER = _Paths.SET_REMINDER;
  static const MEMBERSHIP = _Paths.MEMBERSHIP;
  static const TOP_TESTIMONIALS = _Paths.TOP_TESTIMONIALS;
  static const SESSIONS_TESTIMONIALS = _Paths.SESSIONS_TESTIMONIALS;
  static const SESSION = _Paths.SESSION;
  static const SESSION_DETAILS = _Paths.SESSION_DETAILS;
  static const SESSION_DETAILS_AKASHAY = _Paths.SESSION_DETAILS_AKASHAY;
  static const PROGRAMS_DETAILS = _Paths.PROGRAMS_DETAILS;
  static const BLOG_DETAILS = _Paths.BLOG_DETAILS;
  static const SPIRITUAL_SPOTLIGHT_DETAILS = _Paths.SPIRITUAL_SPOTLIGHT_DETAILS;
  static const FAQ = _Paths.FAQ;
  static const GIVING_BACK = _Paths.GIVING_BACK;
  static const COMMENTS = _Paths.COMMENTS;
  static const PROGRAMS_TESTIMONIALS = _Paths.PROGRAMS_TESTIMONIALS;
  static const RETREATS_TESTIMONIALS = _Paths.RETREATS_TESTIMONIALS;
  static const AKASHA_HEALING_FULL_DETAILS = _Paths.AKASHA_HEALING_FULL_DETAILS;
  static const TEACHINGS1 = _Paths.TEACHINGS1;
  static const TEACHINGS2 = _Paths.TEACHINGS2;
  static const SPLASH = _Paths.SPLASH;
  static const STORY_PAGE = _Paths.STORY_PAGE;
  static const COMING_INTO_ONENESS = _Paths.COMING_INTO_ONENESS;
  static const DIVINE_UNION_BOOK = _Paths.DIVINE_UNION_BOOK;
  static const THANK_YOU = _Paths.THANK_YOU;
  static const VERIFICATION_PASSWORD = _Paths.VERIFICATION_PASSWORD;
  static const VERIFICATION_EMAIL = _Paths.VERIFICATION_EMAIL;
  static const BOOTOMVIEW_TEST = _Paths.BOOTOMVIEW_TEST;
}

abstract class _Paths {
  _Paths._();
  //static const TEST = '/test';
  static const WELCOME_SCREENS = '/welcome-screens';
  static const LOGIN = '/login';
  static const FORGOT_PASSWORD = '/forgot-password';
  static const DASHBOARD = '/dashboard';
  static const MAIN_SCREEN = '/main-screen';
  static const ORACLE_CARDS = '/oracle-cards';
  static const STORE = '/store';
  static const ACCOUNT_SETTINGS = '/account-settings';
  static const SIDE_MENU = '/side-menu';
  static const SACRED_RELATIONSHIPS = '/sacred-relationships';
  static const KARMIC_RELATIONSHIPS = '/karmic-relationships';
  static const TEACHINGS_DETAILS = '/teachings-details';
  static const PROFILE = '/profile';
  static const CHANGE_PASSWORD = '/change-password';
  static const CHANGE_EMAIL = '/change-email';
  static const SPIRITUAL_SPOTLIGHT = '/spiritual-spotlight';
  static const BLOGS_LISTING = '/blogs-listing';
  static const BOOKS_LISTING = '/books-listing';
  static const SESSIONS_LISTING = '/sessions-listing';
  static const PROGRAMS_LISTING = '/programs-listing';
  static const INNER_UNION_ORACLE = '/inner-union-oracle';
  static const SUPPORT = '/support';
  static const BOOK_DETAILS = '/book-details';
  static const ABOUT = '/about';
  static const SET_REMINDER = '/set-reminder';
  static const MEMBERSHIP = '/membership';
  static const TOP_TESTIMONIALS = '/top-testimonials';
  static const SESSIONS_TESTIMONIALS = '/sessions-testimonials';
  static const SESSION = '/session';
  static const SESSION_DETAILS = '/session-details';
  static const SESSION_DETAILS_AKASHAY = '/session-details-akashay';
  static const PROGRAMS_DETAILS = '/programs-details';
  static const BLOG_DETAILS = '/blog-details';
  static const SPIRITUAL_SPOTLIGHT_DETAILS = '/spiritual-spotlight-details';
  static const FAQ = '/faq';
  static const GIVING_BACK = '/giving-back';
  static const COMMENTS = '/comments';
  static const PROGRAMS_TESTIMONIALS = '/programs-testimonials';
  static const RETREATS_TESTIMONIALS = '/retreats-testimonials';
  static const AKASHA_HEALING_FULL_DETAILS = '/akasha-healing-full-details';
  static const TEACHINGS1 = '/teachings1';
  static const TEACHINGS2 = '/teachings2';
  static const SPLASH = '/splash';
  static const STORY_PAGE = '/story-page';
  static const COMING_INTO_ONENESS = '/coming-into-oneness';
  static const DIVINE_UNION_BOOK = '/divine-union-book';
  static const THANK_YOU = '/thank-you';
  static const VERIFICATION_PASSWORD = '/verification-password';
  static const VERIFICATION_EMAIL = '/verification-email';
  static const BOOTOMVIEW_TEST = '/bootomview-test';
}
